apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: desafio-kubernetes
spec:
  hosts:
    - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: desafio-kubernetes # nome do serviço criado no passo anterior.
        port:
          number: 3000 